from datetime import timedelta

SECRET_KEY = "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_FOR_PRODUCTION"

ALGORITHM = "HS256"

ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24

ACCESS_TOKEN_EXPIRE = timedelta(
    minutes=ACCESS_TOKEN_EXPIRE_MINUTES
)